### ISSUE TITLE
database creation and program execution. 

### ISSUE THREAD

**Issue by ashwin962** [souravs17031999/Retinal_blindness_detection_Pytorch#1]
Hello sir. I have an issue in database creation and further execution of the program, I have installed all the necessary software as per your guidance. I am very new to image processing. PLEASE SUPPORT ME and do HELP me, brother. waiting for ur reply

**Comment by souravs17031999** [comment]
Hi, 
if you are having problem in creating the database , check out this link -  https://www.youtube.com/watch?v=mRlXm04S_RY.

If you have any other specific issue, then please do tell and open another issue.
