### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by konakanv** [souravs17031999/Retinal_blindness_detection_Pytorch#13]
I am getting type error while loading one batch of testing set to check the images and labels.
TypeError: pic should be Tensor or ndarray. Got <class 'NoneType'>. please help me to resolve it.

**Comment by souravs17031999** [comment]
@vasu1432 , please post the exact code (links) where you are having issues.

**Comment by konakanv** [comment]
https://colab.research.google.com/drive/1UiO2lU84Ab1_5ssxe2konyNA2uwQpZ9d

**Comment by souravs17031999** [comment]
I don't have access to the colab link, is it same as the project code, then you can share it here.
