### ISSUE TITLE
need ../Desktop/classifier.pt

### ISSUE THREAD

**Issue by Parthkumar22** [souravs17031999/Retinal_blindness_detection_Pytorch#6]
can you please provide me classifier.pt file.

**Comment by souravs17031999** [comment]
Hi, 

Please check here for the mentioned file.
[pretrained weight](https://www.kaggle.com/datasets/souravs17031999/blindness-detection-pretrained-weights-pytorch)

If you find any problems and/or would like to contribute please open a PR with your changes.
